### ISSUE TITLE
.bin files break the script temporarily

### ISSUE THREAD

**Issue by Tempystral** [brossentia/BizHawk-Shuffler#2]
Currently, CD-based games will load just fine, but if the shuffler tries to load the ``.bin`` file associated with the game, the emulator will bug out. The bin and cue files also must be in the same directory in order for the game to read correctly.

- Games with ``.cue`` extensions should have their ``.bin`` counterparts ignored
- Once they're marked as "completed" disk games should have both ``.cue`` and ``.bin`` files moved to the completed directory together.

**Comment by brossentia** [comment]
This should be fixed in the latest merge to master!
