### ISSUE TITLE
Shuffler not activating in BizHawk. (possible user error)

### ISSUE THREAD

**Issue by Vogon42** [brossentia/BizHawk-Shuffler#5]
I'm getting the following message when attempting to run the Shuffler in BizHawk, in the Lua Console. The Shuffler won't become active. Is there a text file that I was supposed to add in the folder? (I am using the dev version of BizHawk linked in the Shuffler description.)

false
ROM: Advance_Wars.gba
ROM: Donkey_Kong_Land.gb
ROM: Dragon Ball - Advanced Adventure (USA).gba
databaseSize is 3 roms!
Initial seed 12345678
Time Limit 5
NLua.Exceptions.LuaScriptException: [string "main"]:250: attempt to index global 'currentGamePlayCount' (a nil value)

**Comment by brossentia** [comment]
Added a folder "PlayCount." This should fix the issue!
